### ISSUE TITLE
Long-pressing on file causes issue BUG

### ISSUE THREAD

**Issue by WindowsFanboy** [duke7553/files-uwp#159]
I long press on a file with my finger and an error appears (not a context menu) prompting me to restart the app or report the issue to the developer. For a fluent designed app which is meant to be more touch friendly this is kinda hard to live with when you don't have a keyboard attached.

**Summary**
Object reference not set to an instance of an object. within T GetCurrentSelectedTabInstance[T]()

**Technical Information**
   at Files.Filesystem.ItemViewModel`1.GetCurrentSelectedTabInstance[T]()
   at Files.Filesystem.ItemViewModel`1.AddItemsToCollectionAsync(String path, Page currentPage)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

**Comment by duke7553** [comment]
@yaichenbaum Can you reproduce this bug while running in a debugger?

**Comment by yaichenbaum** [comment]
I cannot reproduce on the latest version.

**Comment by duke7553** [comment]
@WindowsFanboy Please re-open if you can reproduce this

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
